[project]
name = "iac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible-lint>=25.6.1",
    "ansible>=11.7.0",
    "cryptography>=45.0.4",
]
