---
- name: Pull frontend image
  community.docker.docker_image_pull:
    name: mchegdali/asphub-client
    pull: always

- name: Pull backend image
  community.docker.docker_image_pull:
    name: mchegdali/asphub-server
    pull: always
    
- name: Copy frontend files
  ansible.builtin.copy:
    src: .
    dest: /app/webserver/client
    mode: '0644'

- name: Copy backend files
  ansible.builtin.copy:
    src: .
    dest: /app/webserver/server
    mode: '0644'


- name: Deploy webserver
  community.docker.docker_stack:
    name: webserver
    state: present
    detach: true
    compose: /app/webserver/compose.yml
  environment:
    DOMAIN: '{{ webserver_domain }}'
