groups:
- name: system_alerts
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: HighCpuUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "CPU usage is above 80% for more than 10 minutes on {{ $labels.instance }}."

  - alert: DatabaseHighCpuUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle",instance=~".*database.*"}[5m])) * 100) > 70
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on database node {{ $labels.instance }}"
      description: "Database node CPU usage is above 70% for more than 5 minutes on {{ $labels.instance }}."

  - alert: HighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: "Memory usage is above 85% for more than 10 minutes on {{ $labels.instance }}."

  - alert: DatabaseHighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes{instance=~".*database.*"} / node_memory_MemTotal_bytes{instance=~".*database.*"})) * 100 > 75
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on database node {{ $labels.instance }}"
      description: "Database node memory usage is above 75% for more than 5 minutes on {{ $labels.instance }}."

  - alert: DiskSpaceLow
    expr: (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs"} / node_filesystem_size_bytes{fstype!~"tmpfs|fuse.lxcfs"})) * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Disk space low on {{ $labels.instance }}"
      description: "Disk usage is above 85% on {{ $labels.instance }} ({{ $labels.device }})."

  - alert: DiskSpaceCritical
    expr: (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs"} / node_filesystem_size_bytes{fstype!~"tmpfs|fuse.lxcfs"})) * 100 > 90
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Disk space critical on {{ $labels.instance }}"
      description: "Disk usage is above 90% on {{ $labels.instance }} ({{ $labels.device }})."

  - alert: HighLoadAverage
    expr: node_load15 / on(instance) count by (instance) (node_cpu_seconds_total{mode="idle"}) > 1.5
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High load average on {{ $labels.instance }}"
      description: "Load average is above 1.5x CPU count for more than 10 minutes on {{ $labels.instance }}."

  - alert: HighIOWait
    expr: rate(node_cpu_seconds_total{mode="iowait"}[5m]) * 100 > 5
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High I/O wait on {{ $labels.instance }}"
      description: "I/O wait time is above 5% for more than 10 minutes on {{ $labels.instance }}."

  - alert: MemoryPressure
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Memory pressure on {{ $labels.instance }}"
      description: "Memory usage is above 90% for more than 5 minutes on {{ $labels.instance }}."

  - alert: NodeExporterDown
    expr: up{job="node-exporter"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Node Exporter down on {{ $labels.instance }}"
      description: "Node Exporter has been down for more than 2 minutes on {{ $labels.instance }}."

- name: docker_alerts  
  rules:
  - alert: ContainerDown
    expr: absent(container_last_seen) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container {{ $labels.name }} is down"
      description: "Container {{ $labels.name }} has been down for more than 5 minutes."

  - alert: ContainerCpuUsageWarning
    expr: rate(container_cpu_usage_seconds_total{name!="/"}[5m]) * 100 > 80
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage in container {{ $labels.container_name }}"
      description: "Container {{ $labels.container_name }} CPU usage is above 80% for more than 10 minutes on {{ $labels.instance }}."

  - alert: ContainerCpuUsageCritical
    expr: rate(container_cpu_usage_seconds_total{name!="/"}[5m]) * 100 > 90
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Critical CPU usage in container {{ $labels.container_name }}"
      description: "Container {{ $labels.container_name }} CPU usage is above 90% for more than 5 minutes on {{ $labels.instance }}."

  - alert: ContainerMemoryUsageWarning
    expr: (container_memory_usage_bytes{name!="/"} / container_spec_memory_limit_bytes{name!="/"}) * 100 > 80
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage in container {{ $labels.container_name }}"
      description: "Container {{ $labels.container_name }} memory usage is above 80% for more than 10 minutes on {{ $labels.instance }}."

  - alert: ContainerMemoryUsageCritical
    expr: (container_memory_usage_bytes{name!="/"} / container_spec_memory_limit_bytes{name!="/"}) * 100 > 90
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Critical memory usage in container {{ $labels.container_name }}"
      description: "Container {{ $labels.container_name }} memory usage is above 90% for more than 5 minutes on {{ $labels.instance }}."

  - alert: ContainerRestartingFrequently
    expr: increase(container_start_time_seconds[1h]) > 3
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: "Container {{ $labels.container_name }} restarting frequently"
      description: "Container {{ $labels.container_name }} has restarted more than 3 times in the last hour on {{ $labels.instance }}."

  - alert: ContainerHighNetworkUsage
    expr: rate(container_network_receive_bytes_total[5m]) + rate(container_network_transmit_bytes_total[5m]) > 100000000
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High network usage in container {{ $labels.container_name }}"
      description: "Container {{ $labels.container_name }} network usage is above 100MB/s for more than 10 minutes on {{ $labels.instance }}."

  - alert: ContainerFileSystemUsage
    expr: (container_fs_usage_bytes{name!="/"} / container_fs_limit_bytes{name!="/"}) * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High filesystem usage in container {{ $labels.container_name }}"
      description: "Container {{ $labels.container_name }} filesystem usage is above 85% on {{ $labels.instance }}."

  - alert: cAdvisorDown
    expr: up{job="cadvisor"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "cAdvisor down on {{ $labels.instance }}"
      description: "cAdvisor has been down for more than 2 minutes on {{ $labels.instance }}."

- name: application_correlation_alerts
  rules:
  - alert: ContainerResourcesImpactingPerformance
    expr: |
      (
        rate(container_cpu_usage_seconds_total{name!="/"}[5m]) * 100 > 70
        and
        rate(container_network_receive_bytes_total[5m]) + rate(container_network_transmit_bytes_total[5m]) > 50000000
      ) or (
        (container_memory_usage_bytes{name!="/"} / container_spec_memory_limit_bytes{name!="/"}) * 100 > 70
        and
        rate(container_network_receive_bytes_total[5m]) + rate(container_network_transmit_bytes_total[5m]) > 50000000
      )
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Container {{ $labels.container_name }} resource usage may impact performance"
      description: "Container {{ $labels.container_name }} shows high resource usage (CPU >70% or Memory >70%) combined with high network traffic (>50MB/s) for more than 5 minutes on {{ $labels.instance }}."

  - alert: ContainerResourceExhaustion
    expr: |
      (
        rate(container_cpu_usage_seconds_total{name!="/"}[5m]) * 100 > 95
        or
        (container_memory_usage_bytes{name!="/"} / container_spec_memory_limit_bytes{name!="/"}) * 100 > 95
      )
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Container {{ $labels.container_name }} resource exhaustion"
      description: "Container {{ $labels.container_name }} is experiencing resource exhaustion (CPU >95% or Memory >95%) for more than 2 minutes on {{ $labels.instance }}. This may cause application degradation."

- name: backup_alerts
  rules:
  - alert: BackupJobFailed
    expr: time() - on() group_left() timestamp(backup_last_success_timestamp) > 28800  # 8 hours
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Backup job has failed or not completed"
      description: "The backup job has not completed successfully for more than 8 hours. Last successful backup was {{ $value | humanizeDuration }} ago."

  - alert: BackupMissedSchedule
    expr: time() - on() group_left() timestamp(backup_last_attempt_timestamp) > 90000  # 25 hours
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Backup job missed scheduled execution"
      description: "The backup job has not been attempted for more than 25 hours. Last attempt was {{ $value | humanizeDuration }} ago."

  - alert: BackupRepositoryAccessFailed
    expr: backup_repository_accessible{repository_type!=""} == 0
    for: 5m
    labels:
      severity: critical
      repository_type: "{{ $labels.repository_type }}"
    annotations:
      summary: "Backup repository {{ $labels.repository_type }} is not accessible"
      description: "The {{ $labels.repository_type }} backup repository is not accessible. This affects the 3-2-1 backup strategy."

  - alert: BackupIntegrityCheckFailed
    expr: backup_integrity_check_success{repository_type!=""} == 0
    for: 5m
    labels:
      severity: warning
      repository_type: "{{ $labels.repository_type }}"
    annotations:
      summary: "Backup integrity check failed for {{ $labels.repository_type }} repository"
      description: "The integrity check for the {{ $labels.repository_type }} backup repository has failed. Backup data may be corrupted."

  - alert: BackupDurationTooLong
    expr: backup_duration_seconds > 7200  # 2 hours
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: "Backup job duration is unusually long"
      description: "The backup job took {{ $value | humanizeDuration }} to complete, which is longer than expected (>2 hours)."

  - alert: BackupStorageSpaceLow
    expr: (1 - (backup_repository_free_bytes{repository_type!=""} / backup_repository_total_bytes{repository_type!=""})) * 100 > 85
    for: 10m
    labels:
      severity: warning
      repository_type: "{{ $labels.repository_type }}"
    annotations:
      summary: "Backup storage space low on {{ $labels.repository_type }} repository"
      description: "The {{ $labels.repository_type }} backup repository is {{ $value | printf \"%.1f\" }}% full. Consider cleaning up old backups or expanding storage."

  - alert: BackupStorageSpaceCritical
    expr: (1 - (backup_repository_free_bytes{repository_type!=""} / backup_repository_total_bytes{repository_type!=""})) * 100 > 95
    for: 5m
    labels:
      severity: critical
      repository_type: "{{ $labels.repository_type }}"
    annotations:
      summary: "Backup storage space critical on {{ $labels.repository_type }} repository"
      description: "The {{ $labels.repository_type }} backup repository is {{ $value | printf \"%.1f\" }}% full. Immediate action required to prevent backup failures."

  - alert: BackupComponentFailure
    expr: backup_component_success{component!=""} == 0
    for: 5m
    labels:
      severity: warning
      component: "{{ $labels.component }}"
    annotations:
      summary: "Backup component {{ $labels.component }} failed"
      description: "The backup of {{ $labels.component }} component has failed. This affects data protection for this component."

  - alert: PlakarAgentDown
    expr: up{job="plakar-agent"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Plakar agent is down"
      description: "The Plakar backup agent is not running. This will prevent backup operations from completing successfully."

  - alert: BackupSyncFailed
    expr: backup_sync_success{target_repository!=""} == 0
    for: 5m
    labels:
      severity: critical
      target_repository: "{{ $labels.target_repository }}"
    annotations:
      summary: "Backup synchronization failed to {{ $labels.target_repository }}"
      description: "Failed to synchronize backups to the {{ $labels.target_repository }} repository. This compromises the 3-2-1 backup strategy."

  - alert: NoRecentBackups
    expr: time() - on() group_left() timestamp(backup_last_success_timestamp) > 172800  # 2 days
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "No recent successful backups"
      description: "No successful backup has been completed in the last 2 days. Data protection is severely compromised."

- name: database_alerts
  rules:
  - alert: DatabaseConnectionsHigh
    expr: (sum(pg_stat_activity_count{state!="idle"}) / sum(pg_settings_max_connections)) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High database connection usage"
      description: "Database connection usage is above 80% ({{ $value }}%) for more than 5 minutes."

  - alert: DatabaseSlowQueries
    expr: rate(pg_stat_user_tables_seq_scan[5m]) > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High sequential scan rate detected"
      description: "Database is performing {{ $value }} sequential scans per second, which may indicate missing indexes."

  - alert: DatabaseLockWaits
    expr: pg_stat_database_conflicts > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Database conflicts detected"
      description: "Database conflicts detected: {{ $value }} conflicts in the last period."

  - alert: DatabaseDiskSpaceHigh
    expr: (1 - (node_filesystem_avail_bytes{instance=~".*database.*",mountpoint="/var/lib/postgresql"} / node_filesystem_size_bytes{instance=~".*database.*",mountpoint="/var/lib/postgresql"})) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High database disk usage"
      description: "Database disk usage is above 80% ({{ $value }}%) on {{ $labels.instance }}."