---
# ASPHub Backup Configuration - Solution simplifiée avec conteneur Plakar
# Stratégie 3-2-1 : 3 copies, 2 supports, 1 externe

# Backup scheduling
backup_schedule: "0 2 * * *"  # Daily at 2 AM

# Retention policies
backup_retention_days: 30

# Backup script choice (to avoid Plakar freeze issues)
backup_script: "backup-s3-hybrid.sh"  # Use hybrid script by default
# backup_script: "backup-script.sh"   # Alternative: original Plakar script

# Docker configuration
backup_container_name: "asphub_backup"
backup_stack_name: "asphub_backup"

# Volume configuration (les volumes Docker à sauvegarder)
source_volumes:
  - name: "postgres_data"
    description: "PostgreSQL database data"
  - name: "minio_data"
    description: "MinIO object storage data"

# Plakar repositories configuration (3-2-1 strategy)
backup_repositories:
  local:
    path: "/backup/storage/local"
    description: "Local backup repository (copy #1)"
    
  sftp:
    path: "sftp://{{ vault_backup_sftp_user }}@{{ vault_backup_sftp_host }}{{ vault_backup_sftp_path }}"
    description: "SFTP backup repository (copy #2 - different media)"
    
  s3:
    path: "s3://{{ vault_backup_s3_bucket }}"
    description: "S3 backup repository (copy #3 - offsite)"

# Logging
backup_log_path: "/opt/backup/logs"
backup_config_path: "/opt/backup"