---
# Backup user configuration
backup_user: backup
backup_group: backup

# Backup scheduling
backup_schedule: "0 2 * * *"  # Daily at 2 AM
validation_schedule: "0 6 * * 0"  # Weekly on Sunday at 6 AM

# Retention policies
backup_retention_days: 30
backup_retention_weeks: 12
backup_retention_months: 12

# PostgreSQL configuration
postgres_container_name: "asphub_postgres"
postgres_backup_path: "/opt/backup/data/postgres"

# MinIO configuration  
minio_container_name: "asphub_minio"
minio_backup_path: "/opt/backup/data/minio"
minio_data_path: "/var/lib/docker/volumes/asphub_minio_data/_data"

# Plakar repositories configuration
plakar_repositories:
  local:
    type: "local"
    path: "/opt/backup/repositories/local"
    description: "Local backup repository"
  
  remote_sftp:
    type: "sftp"
    path: "sftp://{{ vault_backup_sftp_user }}@{{ vault_backup_sftp_host }}{{ vault_backup_sftp_path }}"
    description: "Remote SFTP backup repository"
    
  remote_s3:
    type: "s3"
    path: "s3://{{ vault_backup_s3_region }}.amazonaws.com/{{ vault_backup_s3_bucket }}"
    description: "AWS S3 backup repository"

# Backup sources
backup_sources:
  - name: "postgres"
    path: "{{ postgres_backup_path }}"
    description: "PostgreSQL database backups"
    
  - name: "minio"
    path: "{{ minio_backup_path }}"
    description: "MinIO object storage backups"

# Monitoring and alerting
backup_log_file: "/var/log/backup/backup.log"
backup_metrics_file: "/var/log/backup/metrics.json"

# Plakar agent configuration
plakar_agent_user: "{{ backup_user }}"
plakar_agent_socket: "/opt/backup/plakar-agent.sock"