---
- name: Upgrade apt
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true

- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: true

- name: Add Docker APT repository
  ansible.builtin.deb822_repository:
    name: docker
    state: present
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    signed_by: "https://download.docker.com/linux/debian/gpg"
    enabled: true

- name: Install Docker and Docker Compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Install Python dependencies
  ansible.builtin.apt:
    name:
      - python3-cryptography
      - python3-docker
      - python3-jsondiff
    state: present
