---
- name: Pull proxy image
  community.docker.docker_image_pull:
    name: traefik:v3.4

- name: Copy proxy files
  ansible.builtin.copy:
    src: .
    dest: /app/proxy/
    mode: '0644'

- name: Check if proxy network exists
  community.docker.docker_network_info:
    name: proxy
  register: network_info

- name: Create proxy network if not exists
  community.docker.docker_network:
    name: proxy
    driver: overlay
    scope: swarm
    state: present
  when: network_info.network is not defined or network_info.network is none

- name: Deploy proxy
  community.docker.docker_stack:
    name: proxy
    state: present
    detach: true
    compose: /app/proxy/compose.yml
  environment:
    LETSENCRYPT_EMAIL: '{{ letsencrypt_email }}'
    DOMAIN: '{{ domain }}'
    PROXY_USER: '{{ proxy_username }}'
    PROXY_PASSWORD: '{{ proxy_password }}'
