---
- name: Pull shepherd image
  community.docker.docker_image_pull:
    name: containrrr/shepherd

- name: Copy shepherd files
  ansible.builtin.copy:
    src: .
    dest: /app/shepherd/
    mode: '0644'

- name: Deploy shepherd
  community.docker.docker_stack:
    name: shepherd
    state: present
    detach: true
    compose: /app/shepherd/compose.yml
