---
- name: Initialize Docker Swarm on manager
  command: docker swarm init --advertise-addr {{ private_ip }}:{{ swarm_port }}
  when: inventory_hostname in groups['managers']
  register: swarm_init
  changed_when: swarm_init.rc == 0
  failed_when: swarm_init.rc != 0 and "already part of a swarm" not in swarm_init.stderr

- name: Get worker join token
  shell: docker swarm join-token -q worker
  when: inventory_hostname in groups['managers']
  register: worker_token
  changed_when: false

- name: Get manager join token
  shell: docker swarm join-token -q manager
  when: inventory_hostname in groups['managers']
  register: manager_token
  changed_when: false

- name: Join workers to swarm
  command: docker swarm join --token {{ hostvars[groups['managers'][0]]['worker_token']['stdout'] }} {{ hostvars[groups['managers'][0]]['private_ip'] }}:{{ swarm_port }}
  when: inventory_hostname in groups['workers']
  register: join_result
  changed_when: join_result.rc == 0
  failed_when: join_result.rc != 0 and "already part of a swarm" not in join_result.stderr 