---
- name: Initialize Swarm cluster
  community.docker.docker_swarm:
    state: present
    advertise_addr: 192.168.0.100
  register: swarm_manager

- name: Share swarm token to workers
  ansible.builtin.add_host:
    name: swarm_token_worker_holder
    groups:
      - swarm_token_holders
    swarm_token_worker: "{{ swarm_manager.swarm_facts.JoinTokens.Worker }}"
