services:
  webserver:
    image: nginx:1.29.0-alpine
    networks:
      - proxy
    deploy:
      replicas: 2
      
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.webserver.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.webserver.entrypoints=websecure"
        - "traefik.http.routers.webserver.tls=true"
        - "traefik.http.routers.webserver.tls.certresolver=letsencrypt"
        - "traefik.http.services.webserver.loadbalancer.server.port=80"
      placement:
        constraints:
          - node.role == worker

    configs:
      - source: npm_hsts
        target: /app/templates/_hsts.conf


networks:
  proxy:
    external: true

configs:
  npm_hsts:
    external: true
