---
# Handlers pour la solution de backup simplifiée

- name: restart backup stack
  community.docker.docker_stack:
    name: asphub_backup
    state: present
    detach: true
    compose: /opt/backup/compose-backup.yml
    with_registry_auth: true 