services:
  shepherd:
    image: containrrr/shepherd
    environment:
      # Beware YAML gotchas regarding quoting:
      # With KEY: 'VALUE', quotes are part of yaml syntax and thus get stripped
      # but with KEY='VALUE', they are part of the value and stay there,
      # causing problems!
      SLEEP_TIME: "1m"
      TZ: "Europe/Paris"
      VERBOSE: "true"
      IGNORELIST_SERVICES: "label=asphub.autodeploy=false"
      FILTER_SERVICES: "label=asphub.autodeploy=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager