#!/bin/sh

# Parse named arguments
while [ "$#" -gt 0 ]; do
    case "$1" in
        --manager-ip)
            MANAGER_IP="$2"
            shift 2
            ;;
        --worker1-ip)
            WORKER1_IP="$2"
            shift 2
            ;;
        --worker2-ip)
            WORKER2_IP="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 --manager-ip <manager_ip> --worker1-ip <worker1_ip> --worker2-ip <worker2_ip>"
            exit 1
            ;;
    esac
done

# Check if all required arguments were provided
if [ -z "$MANAGER_IP" ] || [ -z "$WORKER1_IP" ] || [ -z "$WORKER2_IP" ]; then
  echo "Error: All IP arguments are required."
  echo "Usage: $0 --manager-ip <manager_ip> --worker1-ip <worker1_ip> --worker2-ip <worker2_ip>"
  exit 1
fi

echo "Manager IP: $MANAGER_IP"
echo "Worker1 IP: $WORKER1_IP"
echo "Worker2 IP: $WORKER2_IP"


# Replace the IPs in the inventory template
echo "# Generated inventory file, do not edit this file" > ./inventory.yml
MANAGER_IP=$MANAGER_IP WORKER1_IP=$WORKER1_IP WORKER2_IP=$WORKER2_IP envsubst < ./templates/inventory_template.yml >> ./inventory.yml

# Ping all hosts
ansible all -m ping

# Run the playbooks
ansible-playbook playbooks/001-setup.yml
ansible-playbook playbooks/002-swarm.yml
ansible-playbook playbooks/003-manager.yml

# TODO: Add webserver and database
# ansible-playbook playbooks/004-workers.yml 
