#cloud-config

package_update: true
package_upgrade: true

keyboard:
  layout: us

timezone: Europe/Paris

users:
  - name: asphub
    lock_passwd: true
    passwd: $6$UU1m7IUP.tqDbnBO$TWRGq5/Ar2oSAHp6otLjPc4EOzksa7mSsZ.5ULzcGJXon1Tf3GIVqBd1YHXJQ5QtbNvcvI8EjlJWVwAEJ4CmU1
    ssh_import_id:
      - gh:mchegdali
      - gh:iSaaMz
      - gh:MoussaST
      - gh:AriaAman
    groups: users,sudo
    sudo: ALL=(ALL) NOPASSWD:ALL

allow_public_ssh_keys: true
ssh_pwauth: false
disable_root: true
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding
