#cloud-config

package_update: true
package_upgrade: true

keyboard:
  layout: us

allow_public_ssh_keys: true
ssh_import_id:
  - gh:mchegdali
  - gh:iSaaMz
  - gh:MoussaST
  - gh:AriaAman

disable_root: true
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding