name: 'Deploy Infrastructure'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: environment
      auto_approve:
        description: 'Auto approve the plan'
        required: true
        default: false
        type: boolean

permissions:
  contents: read
  pull-requests: write

jobs:
  get-environment:
    name: 'Get Environment'
    runs-on: ubuntu-latest
    steps:
      - name: Get Environment
        id: get-environment
        run: |
          ENVIRONMENT=${{ github.event.inputs.environment }}
          ENVIRONMENT=${ENVIRONMENT@L}
          echo "ENVIRONMENT=${ENVIRONMENT}" >> "$GITHUB_OUTPUT"

  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: ${{ github.job.get-environment.outputs.ENVIRONMENT }}
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.11.4"
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./terraform/envs/${{ github.event.inputs.environment }}

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: ./terraform/envs/${{ github.event.inputs.environment }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out=tfplan
      working-directory: ./terraform/envs/${{ github.event.inputs.environment }}

    - name: Save Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: ./terraform/envs/${{ github.event.inputs.environment }}/tfplan
        retention-days: 1

    - name: Show Plan
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      run: terraform show -no-color tfplan
      working-directory: ./terraform/envs/${{ github.event.inputs.environment }}

  terraform-apply:
    name: 'Terraform Apply'
    needs: terraform-plan
    if: github.event.inputs.auto_approve == 'true'
    runs-on: ubuntu-latest
    environment: ${{ github.job.get-environment.outputs.ENVIRONMENT }}
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.11.4"
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Download Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: ./terraform/envs/${{ github.event.inputs.environment }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/envs/${{ github.event.inputs.environment }}

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform/envs/${{ github.event.inputs.environment }}
    

