---
# Monitoring Stack Configuration
monitoring_grafana_domain: grafana.mchegdali.cloud
monitoring_prometheus_domain: prometheus.mchegdali.cloud
monitoring_alertmanager_domain: alertmanager.mchegdali.cloud

# Prometheus Configuration
monitoring_prometheus_version: "v2.55.1"
monitoring_prometheus_retention: "30d"
monitoring_prometheus_storage_size: "5GB"

# Grafana Configuration
monitoring_grafana_version: "11.6.3"
monitoring_grafana_admin_user: "admin"
monitoring_grafana_admin_password: "{{ vault_grafana_admin_password | default('admin123') }}"

# Node Exporter Configuration
monitoring_node_exporter_version: "v1.9.1"

# cAdvisor Configuration
monitoring_cadvisor_version: "v0.52.1"

# AlertManager Configuration
monitoring_alertmanager_version: "v0.28.1"
monitoring_discord_webhook_url: "{{ vault_discord_webhook_url | default('https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN') }}"

# Docker Config Names
grafana_asphub_overview_dashboard_name: "grafana_asphub_overview_dashboard_{{ ansible_date_time.iso8601_basic_short }}"
grafana_asphub_server_dashboard_name: "grafana_asphub_server_dashboard_{{ ansible_date_time.iso8601_basic_short }}"
